name: PHP Composer

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.php_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP ${{ matrix.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        ini-values: error_reporting=-1, display_errors=On, log_errors_max_len=0
        coverage: none
        tools: none
        extensions: curl, mbstring, xml, xmlreader

    - name: Validate composer.json and composer.lock
      run: composer validate
      # run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: |
        rm -f public/tests && ln -s ../tests public/tests
        nohup php -S php -S 127.0.0.1:8081 -t public/ > phpd.log 2>&1 &
        sleep 1
        make citest
